### ISSUE TITLE
Protomata protomata_new.anml does not compile

### ISSUE THREAD

**Issue by kevinaangstadt** [jackwadden/ANMLZoo#1]
When attempting to compile `protomata_new.anml` with apcompile version 1.7-32, I receive the following error:

> Error [-141]: on line 33760 - STE contains an invalid symbol set specification.

It appears that the STE defined on that line has an empty symbol set:

```
<state-transition-element id="__11088__" symbol-set="[]">
      <report-on-match reportcode="640"/>
</state-transition-element>
```

**Comment by jackwadden** [comment]
protomata_new.anml does not exist in ANMLZoo. Closing this ticket.
