### ISSUE TITLE
Brill brill_opt.anml does not compile

### ISSUE THREAD

**Issue by kevinaangstadt** [jackwadden/ANMLZoo#2]
Compiling of Brill benchmark `brill_opt.anml` fails with apcompile 1.7-32:

> Error [-204]: on line 1 - ANML syntax error

Adding additional attributes to the `<anml>` tag appears to fix this:
```
 <anml version="1.0"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```

**Comment by jackwadden** [comment]
brill_opt.anml does not exist in ANMLZoo. Closing this ticket.
